language: node_js
node_js:
- node
cache: npm
script: npm run build
deploy:
  provider: pages
  fqdn: www.johnlawsharrison.com
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  verbose: true
  on:
    branch: master
env:
  global:
    secure: NHoYwXreK6oHe4WL3j0ObgK1434UTW3ZM3KEn+hSKeZO/6RI0ulRUPFu56N7NHNDcrQY9H/770dgjw4O/3n1ZzW9M9fBAQTNtnzxmWLwieb45vrA6d2XlvFJtzeCmq2xl38ivENUC/0TIsflx46pPofYWxSXUoeNw5lEcvVKEffIM1u4wr7OC/bRZxxq+MW+HD0Tgm0M8e1QX/qdGr7NWBbeXyzZZtme0t2VujWzZdojlUi5jhSblrzqJpIMR7ah6IvvYhvCyiVUzA7AIxAT0WOkXBpNVfFu2wS20ZcsEuBG6/yal8mMnqcVFt83o94oH+w/9o8mK32GZvn9S6madQoBsRGepEDDmF444C1zkVmToHaryopkkizE9Ar0as/I/whJbTFeMNnJKrm/jxxsT4Ca+J0CBFQNmpUnR+OgtAlVKgvUSH5UB0sTpyU3YEGAkrEFoXTs0q2Qj1D9qlYhfxACG8QB4+Aj5cHWOgQflNJlLem00vJ34Jv/SirBdFZ2jHSTK382Ii5AgISFnbr756vYqUF/0G6+ZXmriC2iSckz5KrK/QHUoRGNB+5kMTdTwUKVNa4M6enEW0d5tu1gj0nLYfNn5jF8xZBVLqcweArSlZIYDkbRSMQp5t2jlH4MwXkwzL/TUFDX8m304XWSKYoo6tiu+ss/SpazJ6FfNIw=
