language: node_js
node_js:
- node
cache: npm
script: npm run build
deploy:
  provider: pages
  fqdn: www.johnlawsharrison.com
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  verbose: true
  on:
    branch: master
